services:
  stats-server:
    build: ./ewm-stats-service
    container_name: ewm-stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JAVA_OPTS=-Duser.timezone=UTC
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6543:5432"  # внешний 6543 -> внутренний 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ewm_stats_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-main
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JAVA_OPTS=-Duser.timezone=UTC
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ewm_main_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
